#!/usr/bin/env php
<?php

$command = explode(':', basename($argv[0]), 2);
$action = $command[1] ?? ($argv[1] ?? '');

switch ($action) {
    case 'migrate':
        $script = __DIR__ . '/database/migrate.php';
        break;

    case 'execute':
        $script = __DIR__ . '/database/migrations/seed.php';
        break;

    default:
        echo "Commande inconnue.\n";
        echo "Commandes disponibles :\n";
        echo "  php lena:migrate\n";
        echo "  php lena:execute\n";
        exit(1);
}

$command = PHP_BINARY . ' ' . escapeshellarg($script);
passthru($command, $status);
exit($status);